//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationAuthorization
    {
        public int AppId { get; set; }
        public string AppName { get; set; }
        public string AppSecret { get; set; }
        public string AppSafeCode { get; set; }
        public string AppServerIps { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> AppStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
