//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_management
    {
        public int contract { get; set; }
        public decimal loan_number { get; set; }
        public int targetid { get; set; }
        public string lender_name { get; set; }
        public string lender_username { get; set; }
        public Nullable<int> lender_registerid { get; set; }
        public string lender_id_card { get; set; }
        public string lenders_account_name { get; set; }
        public string lender_bank_account { get; set; }
        public string lender_bank { get; set; }
        public string lender_address { get; set; }
        public string lenders_telephone { get; set; }
        public string lenders_email { get; set; }
        public Nullable<System.DateTime> lendres_date_contract { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public string borrower_name { get; set; }
        public string borrower_username { get; set; }
        public string borrower_id_card { get; set; }
        public string borrower_account_name { get; set; }
        public string borrower_bank_account { get; set; }
        public string borrower_date_contract { get; set; }
        public string borrower_bank { get; set; }
        public string witness_name { get; set; }
        public string witness_address { get; set; }
        public string witness_telephone { get; set; }
        public string witness_agent { get; set; }
        public Nullable<int> witness_admid { get; set; }
        public string witness_username { get; set; }
        public string witness_id_card { get; set; }
        public Nullable<System.DateTime> witness_date_contract { get; set; }
        public string surety_company_name { get; set; }
        public string guarantee_business_icense { get; set; }
        public string ensure_address { get; set; }
        public string guarantee_legal_representative { get; set; }
        public string guarantor_agent { get; set; }
        public Nullable<int> guarantor_companyid { get; set; }
        public string guarantor_agent_usernqme { get; set; }
        public string guarantor_agent_id_card { get; set; }
        public Nullable<System.DateTime> guarantor_agent_idate_contract { get; set; }
        public string contract_money { get; set; }
        public string counselling_service { get; set; }
        public Nullable<decimal> contract_amount { get; set; }
        public string suretyship_contract { get; set; }
        public string mode_payment { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> contract_type { get; set; }
        public string contractpath { get; set; }
        public Nullable<int> bid_records_id { get; set; }
    
        public virtual hx_borrowing_target hx_borrowing_target { get; set; }
    }
}
