//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrabIphone
    {
        public int ID { get; set; }
        public Nullable<int> RegrsterID { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<int> LuckDrawState { get; set; }
        public Nullable<int> WinningState { get; set; }
        public Nullable<System.DateTime> WinningTime { get; set; }
        public Nullable<int> TargetID { get; set; }
        public Nullable<int> BidRecordsID { get; set; }
        public string InvestmentAmount { get; set; }
    }
}
