//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guarantee_way
    {
        public int guarantee_way_id { get; set; }
        public string guarantee_way_name { get; set; }
        public Nullable<decimal> amount_guaranteed { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
