//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_AppUpdatePackage
    {
        public long id { get; set; }
        public string Code { get; set; }
        public string Platform { get; set; }
        public string Version { get; set; }
        public int UpdateLevel { get; set; }
        public string Description { get; set; }
        public string DependCode { get; set; }
        public string Channel { get; set; }
        public string ValideCode { get; set; }
        public string VirtualPath { get; set; }
        public string Ways { get; set; }
        public int IsEnable { get; set; }
        public long DownloadCount { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
