//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_ActivityTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hx_ActivityTable()
        {
            this.hx_SMSContext = new HashSet<hx_SMSContext>();
            this.hx_UserAct = new HashSet<hx_UserAct>();
        }
    
        public int ActID { get; set; }
        public Nullable<int> ActTypeId { get; set; }
        public Nullable<int> RewTypeID { get; set; }
        public string ActName { get; set; }
        public Nullable<int> ActUser { get; set; }
        public Nullable<System.DateTime> ActStarttime { get; set; }
        public Nullable<System.DateTime> ActEndtime { get; set; }
        public string ActRule { get; set; }
        public Nullable<int> ActState { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string ActTargetPlatform { get; set; }
    
        public virtual hx_ActivityType hx_ActivityType { get; set; }
        public virtual hx_RewardType hx_RewardType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hx_SMSContext> hx_SMSContext { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hx_UserAct> hx_UserAct { get; set; }
    }
}
