//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_borrower_guarantor_picture
    {
        public int borrower_guarantor_picture_id { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<int> type_picture { get; set; }
        public string picture_path { get; set; }
        public string picture_name { get; set; }
        public Nullable<System.DateTime> uploadtime { get; set; }
        public Nullable<int> picture_index { get; set; }
    }
}
