//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_Bid_records
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hx_Bid_records()
        {
            this.hx_income_statement = new HashSet<hx_income_statement>();
        }
    
        public int bid_records_id { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<decimal> loan_number { get; set; }
        public Nullable<decimal> annual_interest_rate { get; set; }
        public Nullable<int> current_period { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<System.DateTime> value_date { get; set; }
        public Nullable<System.DateTime> investment_maturity { get; set; }
        public Nullable<System.DateTime> invest_time { get; set; }
        public Nullable<int> invest_state { get; set; }
        public Nullable<int> flow_return { get; set; }
        public Nullable<decimal> repayment_amount { get; set; }
        public Nullable<System.DateTime> repayment_period { get; set; }
        public Nullable<int> investor_registerid { get; set; }
        public Nullable<int> payment_status { get; set; }
        public Nullable<decimal> withoutinterest { get; set; }
        public Nullable<decimal> haveinterest { get; set; }
        public Nullable<int> contractid { get; set; }
        public string contractpath { get; set; }
        public string invitationcode { get; set; }
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<int> ordstate { get; set; }
        public Nullable<int> IsLoans { get; set; }
        public Nullable<decimal> JiaxiNum { get; set; }
        public Nullable<decimal> BonusAmt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hx_income_statement> hx_income_statement { get; set; }
    }
}
