//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_bonding_company
    {
        public int companyid { get; set; }
        public string company_name { get; set; }
        public Nullable<decimal> registered_capital { get; set; }
        public Nullable<System.DateTime> Date_incorporation { get; set; }
        public string company_address { get; set; }
        public string company_profile { get; set; }
        public string business_licence { get; set; }
        public string business_certificate { get; set; }
        public string contract_covers { get; set; }
        public string contract_bottom { get; set; }
        public string legal_representative { get; set; }
        public string agent { get; set; }
        public string agent_name { get; set; }
        public string agent_id_card { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string Tax_NO { get; set; }
        public Nullable<int> GuarType { get; set; }
        public string UsrCustId { get; set; }
        public string AuditStat { get; set; }
        public string TrxId { get; set; }
        public string OpenBandkId { get; set; }
        public string CardId { get; set; }
        public string UsrId { get; set; }
        public string company_Url { get; set; }
        public string company_tel { get; set; }
    }
}
