//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_borrowing_target_detailed
    {
        public int target_detailed_id { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public Nullable<int> targetid { get; set; }
        public string item_details { get; set; }
        public string borrower_circumstances { get; set; }
        public string borrower_base_material { get; set; }
        public string use_funds { get; set; }
        public string independent_advice { get; set; }
        public string guarantee_agency_views { get; set; }
        public string risk_control_measures { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    
        public virtual hx_borrowing_target hx_borrowing_target { get; set; }
    }
}
