//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_Capital_account_water
    {
        public int account_water_id { get; set; }
        public Nullable<int> membertable_registerid { get; set; }
        public Nullable<decimal> income { get; set; }
        public Nullable<decimal> expenditure { get; set; }
        public Nullable<System.DateTime> time_of_occurrence { get; set; }
        public Nullable<decimal> account_balance { get; set; }
        public Nullable<int> types_Finance { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> keyid { get; set; }
        public string remarks { get; set; }
    
        public virtual hx_member_table hx_member_table { get; set; }
    }
}
