//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_Channel_AdminUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hx_Channel_AdminUser()
        {
            this.hx_Channel = new HashSet<hx_Channel>();
        }
    
        public int AdminUserID { get; set; }
        public string AdminUserName { get; set; }
        public string AdminUserPassword { get; set; }
        public string TrueName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<byte> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hx_Channel> hx_Channel { get; set; }
    }
}
