//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_DepUserLimit1
    {
        public int id { get; set; }
        public Nullable<int> limitType { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> adminUserId { get; set; }
        public Nullable<int> limitId { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
