//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_member_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hx_member_table()
        {
            this.hx_borrowing_target = new HashSet<hx_borrowing_target>();
            this.hx_Capital_account_water = new HashSet<hx_Capital_account_water>();
            this.hx_td_usrlogininfo = new HashSet<hx_td_usrlogininfo>();
            this.hx_UserAct = new HashSet<hx_UserAct>();
        }
    
        public int registerid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string realname { get; set; }
        public string UsrCustId { get; set; }
        public string iD_number { get; set; }
        public string transactionpassword { get; set; }
        public Nullable<int> istransactionpassword { get; set; }
        public Nullable<int> ismobile { get; set; }
        public Nullable<int> isrealname { get; set; }
        public Nullable<int> isbankcard { get; set; }
        public Nullable<int> isemail { get; set; }
        public Nullable<int> userstate { get; set; }
        public decimal account_total_assets { get; set; }
        public decimal available_balance { get; set; }
        public decimal collect_total_amount { get; set; }
        public decimal frozen_sum { get; set; }
        public Nullable<int> open_tonto_account { get; set; }
        public string tonto_account_user { get; set; }
        public Nullable<int> usertypes { get; set; }
        public Nullable<System.DateTime> registration_time { get; set; }
        public Nullable<System.DateTime> lastlogintime { get; set; }
        public string lastloginIP { get; set; }
        public Nullable<int> customserviceid { get; set; }
        public string homephone { get; set; }
        public string contactaddress { get; set; }
        public string zipcode { get; set; }
        public string qq { get; set; }
        public string msn { get; set; }
        public string invitedcode { get; set; }
        public string UsrId { get; set; }
        public Nullable<int> useridentity { get; set; }
        public string CopName { get; set; }
        public Nullable<int> Channelsource { get; set; }
        public string Tid { get; set; }
        public string WXAppId { get; set; }
        public Nullable<int> CommNum { get; set; }
        public Nullable<int> RechargeNum { get; set; }
        public Nullable<int> CashNum { get; set; }
        public Nullable<int> InvestNum { get; set; }
        public string avatar { get; set; }
        public Nullable<int> LostInvitation { get; set; }
        public Nullable<int> LoginNum { get; set; }
        public Nullable<System.DateTime> calltime { get; set; }
        public string ExtendCode { get; set; }
        public string channel_invitedcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hx_borrowing_target> hx_borrowing_target { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hx_Capital_account_water> hx_Capital_account_water { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hx_td_usrlogininfo> hx_td_usrlogininfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hx_UserAct> hx_UserAct { get; set; }
    }
}
