//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_Mention_charges
    {
        public int mention_charges_id { get; set; }
        public string mention_charges_name { get; set; }
        public Nullable<decimal> minimum_amount { get; set; }
        public Nullable<decimal> maximum_amount { get; set; }
        public Nullable<decimal> fees { get; set; }
        public Nullable<int> fees_unit { get; set; }
    }
}
