//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_QuanmamaRecord
    {
        public int ID { get; set; }
        public string RegisterMobile { get; set; }
        public string UsrCustID { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public System.DateTime InvestTime { get; set; }
        public decimal InvestMoney { get; set; }
        public decimal TotalInvestMoney { get; set; }
        public string InvestPeriod { get; set; }
        public decimal GiftMoney { get; set; }
        public int SendState { get; set; }
        public int Creater { get; set; }
        public System.DateTime CraeteTime { get; set; }
        public Nullable<int> Sender { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
    }
}
