//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_Recharge_history
    {
        public int recharge_history_id { get; set; }
        public Nullable<int> membertable_registerid { get; set; }
        public Nullable<decimal> recharge_amount { get; set; }
        public Nullable<System.DateTime> recharge_time { get; set; }
        public Nullable<decimal> account_amount { get; set; }
        public string order_No { get; set; }
        public Nullable<int> recharge_condition { get; set; }
        public string recharge_bank { get; set; }
    }
}
