//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_td_reviewremarks
    {
        public int reviewid { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<int> tender_state { get; set; }
        public string reviewremarks { get; set; }
        public Nullable<System.DateTime> reviewtime { get; set; }
        public Nullable<int> admin_operator { get; set; }
    }
}
