//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_td_UserCash
    {
        public int UserCashId { get; set; }
        public Nullable<int> registerid { get; set; }
        public string UsrCustId { get; set; }
        public Nullable<decimal> TransAmt { get; set; }
        public Nullable<decimal> FeeAmt { get; set; }
        public string OrdId { get; set; }
        public Nullable<System.DateTime> OrdIdTime { get; set; }
        public Nullable<int> OrdIdState { get; set; }
        public Nullable<System.DateTime> OperTime { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TransState { get; set; }
        public string OpenAcctId { get; set; }
        public string OpenBankId { get; set; }
        public string FeeObjFlag { get; set; }
        public Nullable<decimal> PayAmt { get; set; }
        public string CashChl { get; set; }
    }
}
