//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_td_Myborrow
    {
        public int Myborrowid { get; set; }
        public string Username { get; set; }
        public string userTel { get; set; }
        public string BorrAMT { get; set; }
        public string BorrPurposes { get; set; }
        public string Area { get; set; }
        public string CompName { get; set; }
        public string Industry { get; set; }
        public string RegCapital { get; set; }
        public Nullable<int> TimeLimit { get; set; }
        public Nullable<System.DateTime> FoundingTime { get; set; }
        public Nullable<int> Mortgage { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<int> BorrType { get; set; }
        public Nullable<int> BorrState { get; set; }
    }
}
