//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_td_usrlogininfo
    {
        public int loginid { get; set; }
        public Nullable<int> registerid { get; set; }
        public Nullable<System.DateTime> logintime { get; set; }
        public string Loginusrname { get; set; }
        public string loginusrpass { get; set; }
        public Nullable<int> loginstate { get; set; }
        public string loginIP { get; set; }
        public string logincity { get; set; }
        public Nullable<int> loginsource { get; set; }
    
        public virtual hx_member_table hx_member_table { get; set; }
    }
}
