//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_Test_records
    {
        public int TrecordsID { get; set; }
        public string Username { get; set; }
        public string mobile { get; set; }
        public Nullable<decimal> amt { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> targetid { get; set; }
    }
}
