//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_td_Phone_records
    {
        public int recordsid { get; set; }
        public string recordcontext { get; set; }
        public Nullable<System.DateTime> recordtime { get; set; }
        public Nullable<int> registerid { get; set; }
        public Nullable<int> adminid { get; set; }
        public string gtType { get; set; }
        public string problemType { get; set; }
    }
}
