//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_td_Loan_records
    {
        public int Loan_records_id { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<int> bid_records_id { get; set; }
        public string InCustId { get; set; }
        public string OutCustId { get; set; }
        public Nullable<decimal> LoanAMT { get; set; }
        public string LoanOrdId { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<decimal> Free { get; set; }
        public string DivDetails { get; set; }
        public string SubOrdid { get; set; }
        public Nullable<System.DateTime> SubOrdDate { get; set; }
        public string unFreezeOrdId { get; set; }
        public string FreezeTrxId { get; set; }
        public Nullable<decimal> bid_orderid { get; set; }
    }
}
