//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_td_LLpay_re_cash
    {
        public int re_cashid { get; set; }
        public string OrdId { get; set; }
        public string no_order { get; set; }
        public string OutAcctId { get; set; }
        public string InAcctId { get; set; }
        public Nullable<decimal> TransAmt { get; set; }
        public Nullable<int> h_state { get; set; }
        public Nullable<int> htype { get; set; }
        public Nullable<System.DateTime> OrdTime { get; set; }
        public Nullable<int> Usrid { get; set; }
        public string Remarks { get; set; }
    }
}
