//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_td_Bank
    {
        public int Bankid { get; set; }
        public string BankName { get; set; }
        public string OpenBankId { get; set; }
        public string CardImage { get; set; }
        public Nullable<int> Isquick { get; set; }
        public Nullable<int> Isordinary { get; set; }
        public Nullable<int> isGren { get; set; }

        /// <summary>
        /// 单笔限额
        /// </summary>
        public Nullable<decimal> SingleTransQuota { get; set; }

        /// <summary>
        /// 单日限额
        /// </summary>
        public Nullable<decimal> CardDailyTransQuota { get; set; }

        /// <summary>
        /// 限额列表图片路径
        /// </summary>
        public string CardImageNew { get; set; }
    }
}
