//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hx_UserAct
    {
        public int UserAct { get; set; }
        public Nullable<int> registerid { get; set; }
        public Nullable<int> ActID { get; set; }
        public Nullable<int> RewTypeID { get; set; }
        public Nullable<int> ActTypeId { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> Uselower { get; set; }
        public Nullable<decimal> Usehight { get; set; }
        public Nullable<System.DateTime> AmtEndtime { get; set; }
        public Nullable<int> AmtUses { get; set; }
        public Nullable<int> UseState { get; set; }
        public Nullable<int> AmtProid { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
        public Nullable<int> ISSmsOne { get; set; }
        public Nullable<int> IsSmsThree { get; set; }
        public Nullable<int> IsSmsSeven { get; set; }
        public Nullable<int> isSmsFifteen { get; set; }
        public Nullable<int> isSmsSixteen { get; set; }
        public Nullable<decimal> OrderID { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string Title { get; set; }
        public string UseLifeLoan { get; set; }
    
        public virtual hx_ActivityTable hx_ActivityTable { get; set; }
        public virtual hx_ActivityType hx_ActivityType { get; set; }
        public virtual hx_member_table hx_member_table { get; set; }
        public virtual hx_RewardType hx_RewardType { get; set; }
    }
}
