//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class chuangtouEntities : DbContext
    {
        public chuangtouEntities()
            : base("name=chuangtouEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<bonus_account> bonus_account { get; set; }
        public virtual DbSet<bonus_account_water> bonus_account_water { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<Contract_management> Contract_management { get; set; }
        public virtual DbSet<guarantee_way> guarantee_way { get; set; }
        public virtual DbSet<hx_Activity_schedule> hx_Activity_schedule { get; set; }
        public virtual DbSet<hx_Bid_records> hx_Bid_records { get; set; }
        public virtual DbSet<hx_bonding_company> hx_bonding_company { get; set; }
        public virtual DbSet<hx_borrower_guarantor_picture> hx_borrower_guarantor_picture { get; set; }
        public virtual DbSet<hx_borrowing_target> hx_borrowing_target { get; set; }
        public virtual DbSet<hx_borrowing_target_detailed> hx_borrowing_target_detailed { get; set; }
        public virtual DbSet<hx_Capital_account_water> hx_Capital_account_water { get; set; }
        public virtual DbSet<hx_CashAwards> hx_CashAwards { get; set; }
        public virtual DbSet<hx_Contract_template> hx_Contract_template { get; set; }
        public virtual DbSet<hx_contract_type> hx_contract_type { get; set; }
        public virtual DbSet<hx_income_statement> hx_income_statement { get; set; }
        public virtual DbSet<hx_investsearch> hx_investsearch { get; set; }
        public virtual DbSet<hx_member_table> hx_member_table { get; set; }
        public virtual DbSet<hx_Mention_charges> hx_Mention_charges { get; set; }
        public virtual DbSet<hx_Project_type> hx_Project_type { get; set; }
        public virtual DbSet<hx_Recharge_history> hx_Recharge_history { get; set; }
        public virtual DbSet<hx_repayment_plan> hx_repayment_plan { get; set; }
        public virtual DbSet<hx_td_about_news> hx_td_about_news { get; set; }
        public virtual DbSet<hx_td_Ad> hx_td_Ad { get; set; }
        public virtual DbSet<hx_td_adminuser> hx_td_adminuser { get; set; }
        public virtual DbSet<hx_td_Bank> hx_td_Bank { get; set; }
        public virtual DbSet<hx_td_department> hx_td_department { get; set; }
        public virtual DbSet<hx_td_department_child> hx_td_department_child { get; set; }
        public virtual DbSet<hx_td_frozen> hx_td_frozen { get; set; }
        public virtual DbSet<hx_td_Links> hx_td_Links { get; set; }
        public virtual DbSet<hx_td_LL_cash> hx_td_LL_cash { get; set; }
        public virtual DbSet<hx_td_LLBack> hx_td_LLBack { get; set; }
        public virtual DbSet<hx_td_LLPay_bindCard> hx_td_LLPay_bindCard { get; set; }
        public virtual DbSet<hx_td_LLpay_city> hx_td_LLpay_city { get; set; }
        public virtual DbSet<hx_td_LLpay_re_cash> hx_td_LLpay_re_cash { get; set; }
        public virtual DbSet<hx_td_LLpay_Recharge> hx_td_LLpay_Recharge { get; set; }
        public virtual DbSet<hx_td_Loan_records> hx_td_Loan_records { get; set; }
        public virtual DbSet<hx_td_LoginInfo> hx_td_LoginInfo { get; set; }
        public virtual DbSet<hx_td_menu> hx_td_menu { get; set; }
        public virtual DbSet<hx_td_Myborrow> hx_td_Myborrow { get; set; }
        public virtual DbSet<hx_td_Phone_records> hx_td_Phone_records { get; set; }
        public virtual DbSet<hx_td_reviewremarks> hx_td_reviewremarks { get; set; }
        public virtual DbSet<hx_td_SMS_record> hx_td_SMS_record { get; set; }
        public virtual DbSet<hx_td_SMSEmail> hx_td_SMSEmail { get; set; }
        public virtual DbSet<hx_td_System_message> hx_td_System_message { get; set; }
        public virtual DbSet<hx_td_UserCash> hx_td_UserCash { get; set; }
        public virtual DbSet<hx_td_Userinvitation> hx_td_Userinvitation { get; set; }
        public virtual DbSet<hx_td_web_Ad_type> hx_td_web_Ad_type { get; set; }
        public virtual DbSet<hx_td_web_type> hx_td_web_type { get; set; }
        public virtual DbSet<hx_Test_records> hx_Test_records { get; set; }
        public virtual DbSet<hx_UsrBindCardC> hx_UsrBindCardC { get; set; }
        public virtual DbSet<Overdue_repayment> Overdue_repayment { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<hx_td_admin_role> hx_td_admin_role { get; set; }
        public virtual DbSet<V_AD_type> V_AD_type { get; set; }
        public virtual DbSet<v_admin_role_menu> v_admin_role_menu { get; set; }
        public virtual DbSet<v_adminuser_department> v_adminuser_department { get; set; }
        public virtual DbSet<V_Bid_Frozen> V_Bid_Frozen { get; set; }
        public virtual DbSet<V_Bid_income_statement> V_Bid_income_statement { get; set; }
        public virtual DbSet<V_bid_records_bonus_account> V_bid_records_bonus_account { get; set; }
        public virtual DbSet<V_bonus_account> V_bonus_account { get; set; }
        public virtual DbSet<V_bonus_account_water> V_bonus_account_water { get; set; }
        public virtual DbSet<V_borrow_repayment_plan> V_borrow_repayment_plan { get; set; }
        public virtual DbSet<V_borrowing_Bid_records_income_statement> V_borrowing_Bid_records_income_statement { get; set; }
        public virtual DbSet<V_borrowing_Bid_records_income_statement_uc> V_borrowing_Bid_records_income_statement_uc { get; set; }
        public virtual DbSet<V_borrowing_target_addlist> V_borrowing_target_addlist { get; set; }
        public virtual DbSet<V_borrowing_target_bonding> V_borrowing_target_bonding { get; set; }
        public virtual DbSet<V_borrowing_target_review> V_borrowing_target_review { get; set; }
        public virtual DbSet<V_contract_type_template> V_contract_type_template { get; set; }
        public virtual DbSet<V_hx_Bid_records_borrowing_target> V_hx_Bid_records_borrowing_target { get; set; }
        public virtual DbSet<V_hx_Bid_records_borrowing_target_uc> V_hx_Bid_records_borrowing_target_uc { get; set; }
        public virtual DbSet<V_incomeborr_count> V_incomeborr_count { get; set; }
        public virtual DbSet<V_LL_Cash_User> V_LL_Cash_User { get; set; }
        public virtual DbSet<V_LLBack_Card_List> V_LLBack_Card_List { get; set; }
        public virtual DbSet<V_LLPay_Re> V_LLPay_Re { get; set; }
        public virtual DbSet<V_Phone_records> V_Phone_records { get; set; }
        public virtual DbSet<V_Recharge_user_bank> V_Recharge_user_bank { get; set; }
        public virtual DbSet<V_Repayment_plan_loan_records> V_Repayment_plan_loan_records { get; set; }
        public virtual DbSet<V_SMS_Record> V_SMS_Record { get; set; }
        public virtual DbSet<V_td_LLpay_bank> V_td_LLpay_bank { get; set; }
        public virtual DbSet<V_type_news> V_type_news { get; set; }
        public virtual DbSet<V_UserCash_Bank> V_UserCash_Bank { get; set; }
        public virtual DbSet<V_UserInvitation> V_UserInvitation { get; set; }
        public virtual DbSet<V_UsrBindCardBank> V_UsrBindCardBank { get; set; }
        public virtual DbSet<V_yaoqin_count> V_yaoqin_count { get; set; }
        public virtual DbSet<hx_ActivityTable> hx_ActivityTable { get; set; }
        public virtual DbSet<hx_ActivityType> hx_ActivityType { get; set; }
        public virtual DbSet<hx_RewardType> hx_RewardType { get; set; }
        public virtual DbSet<hx_SMSContext> hx_SMSContext { get; set; }
        public virtual DbSet<hx_UserAct> hx_UserAct { get; set; }
    
        public virtual int GetPageIndex(string tblName, string strGetFields, string fldName, Nullable<int> pageSize, Nullable<int> pageIndex, string strWhere, string sort, ObjectParameter recordCount)
        {
            var tblNameParameter = tblName != null ?
                new ObjectParameter("tblName", tblName) :
                new ObjectParameter("tblName", typeof(string));
    
            var strGetFieldsParameter = strGetFields != null ?
                new ObjectParameter("strGetFields", strGetFields) :
                new ObjectParameter("strGetFields", typeof(string));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var strWhereParameter = strWhere != null ?
                new ObjectParameter("strWhere", strWhere) :
                new ObjectParameter("strWhere", typeof(string));
    
            var sortParameter = sort != null ?
                new ObjectParameter("Sort", sort) :
                new ObjectParameter("Sort", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetPageIndex", tblNameParameter, strGetFieldsParameter, fldNameParameter, pageSizeParameter, pageIndexParameter, strWhereParameter, sortParameter, recordCount);
        }
    
        public virtual int GetPageRecord(string tblName, string strGetFields, string fldName, Nullable<int> pageSize, Nullable<int> pageIndex, string strWhere, ObjectParameter recordCount)
        {
            var tblNameParameter = tblName != null ?
                new ObjectParameter("tblName", tblName) :
                new ObjectParameter("tblName", typeof(string));
    
            var strGetFieldsParameter = strGetFields != null ?
                new ObjectParameter("strGetFields", strGetFields) :
                new ObjectParameter("strGetFields", typeof(string));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var strWhereParameter = strWhere != null ?
                new ObjectParameter("strWhere", strWhere) :
                new ObjectParameter("strWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetPageRecord", tblNameParameter, strGetFieldsParameter, fldNameParameter, pageSizeParameter, pageIndexParameter, strWhereParameter, recordCount);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int usp_PagingLarge(string tableNames, string primaryKey, string fields, Nullable<int> pageSize, Nullable<int> currentPage, string filter, string group, string order)
        {
            var tableNamesParameter = tableNames != null ?
                new ObjectParameter("TableNames", tableNames) :
                new ObjectParameter("TableNames", typeof(string));
    
            var primaryKeyParameter = primaryKey != null ?
                new ObjectParameter("PrimaryKey", primaryKey) :
                new ObjectParameter("PrimaryKey", typeof(string));
    
            var fieldsParameter = fields != null ?
                new ObjectParameter("Fields", fields) :
                new ObjectParameter("Fields", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("CurrentPage", currentPage) :
                new ObjectParameter("CurrentPage", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("Filter", filter) :
                new ObjectParameter("Filter", typeof(string));
    
            var groupParameter = group != null ?
                new ObjectParameter("Group", group) :
                new ObjectParameter("Group", typeof(string));
    
            var orderParameter = order != null ?
                new ObjectParameter("Order", order) :
                new ObjectParameter("Order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_PagingLarge", tableNamesParameter, primaryKeyParameter, fieldsParameter, pageSizeParameter, currentPageParameter, filterParameter, groupParameter, orderParameter);
        }
    }
}
