//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics_Member
    {
        public int StatisticsId { get; set; }
        public System.DateTime StatisticsDate { get; set; }
        public int RegistCount { get; set; }
        public int RealNameCount { get; set; }
        public int InvestCount { get; set; }
        public int IsFinish { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
