//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics_ActiveSepteberCashback
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int InvestTerm { get; set; }
        public int InvestTimes { get; set; }
        public decimal InvestTotalAmount { get; set; }
        public decimal CashbackAmount { get; set; }
        public int HasCashback { get; set; }
    }
}
