//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ACT
    {
        public int UserAct { get; set; }
        public Nullable<int> RewTypeID { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> Uselower { get; set; }
        public Nullable<decimal> Usehight { get; set; }
        public Nullable<System.DateTime> AmtEndtime { get; set; }
        public Nullable<int> UseState { get; set; }
        public Nullable<int> AmtProid { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
        public Nullable<int> ISSmsOne { get; set; }
        public Nullable<int> IsSmsThree { get; set; }
        public Nullable<int> IsSmsSeven { get; set; }
        public Nullable<int> isSmsFifteen { get; set; }
        public Nullable<int> isSmsSixteen { get; set; }
        public Nullable<decimal> OrderID { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<System.DateTime> ActStarttime { get; set; }
        public Nullable<System.DateTime> ActEndtime { get; set; }
        public Nullable<int> ActState { get; set; }
        public string ActName { get; set; }
        public string username { get; set; }
        public string mobile { get; set; }
        public Nullable<int> useridentity { get; set; }
        public Nullable<int> Channelsource { get; set; }
        public int ActTypeId { get; set; }
        public int ActID { get; set; }
        public string realname { get; set; }
        public Nullable<System.DateTime> registration_time { get; set; }
        public Nullable<int> registerid { get; set; }
    }
}
