//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AD_type
    {
        public int Adid { get; set; }
        public string AdName { get; set; }
        public Nullable<System.DateTime> Adcreatetime { get; set; }
        public Nullable<int> AdState { get; set; }
        public Nullable<int> AdTypeId { get; set; }
        public string AdLink { get; set; }
        public string AdPath { get; set; }
        public string AdtypeName { get; set; }
    }
}
