//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_adminuser_department
    {
        public int adminuserid { get; set; }
        public string adminuser { get; set; }
        public string userpass { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string trueName { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string phone_number { get; set; }
        public Nullable<System.DateTime> lastLoginTime { get; set; }
        public string lastLoginIP { get; set; }
        public Nullable<int> loginTimes { get; set; }
        public string worknum { get; set; }
        public string sex { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> area_id { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> rootid { get; set; }
        public string department_name { get; set; }
    }
}
