//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_bid_records_bonus_account
    {
        public int bid_records_id { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<decimal> loan_number { get; set; }
        public Nullable<decimal> annual_interest_rate { get; set; }
        public Nullable<int> current_period { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<int> proid { get; set; }
        public int bonus_account_id { get; set; }
        public Nullable<int> activity_schedule_id { get; set; }
        public string activity_schedule_name { get; set; }
        public Nullable<decimal> amount_of_reward { get; set; }
        public Nullable<decimal> use_lower_limit { get; set; }
        public Nullable<int> reward { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<int> membertable_registerid { get; set; }
        public Nullable<int> reward_state { get; set; }
    }
}
