//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Bid_records_Lost
    {
        public int bid_records_id { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<System.DateTime> invest_time { get; set; }
        public string borrowing_title { get; set; }
        public Nullable<decimal> borrowing_balance { get; set; }
        public Nullable<decimal> annual_interest_rate { get; set; }
        public Nullable<int> investor_registerid { get; set; }
        public string username { get; set; }
        public string mobile { get; set; }
        public string realname { get; set; }
        public Nullable<int> ordstate { get; set; }
        public string UsrCustId { get; set; }
        public string FrozenidNo { get; set; }
        public string FreezeTrxId { get; set; }
    }
}
