//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Bid_Frozen
    {
        public int bid_records_id { get; set; }
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<int> ordstate { get; set; }
        public int Frozenid { get; set; }
        public string UsrCustId { get; set; }
        public string FreezeTrxId { get; set; }
        public Nullable<int> FrozenState { get; set; }
        public string FrozenidNo { get; set; }
        public Nullable<int> targetid { get; set; }
    }
}
