//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_borrowing_target_bonding
    {
        public int targetid { get; set; }
        public decimal loan_number { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public string borrowing_title { get; set; }
        public Nullable<decimal> annual_interest_rate { get; set; }
        public Nullable<decimal> borrowing_balance { get; set; }
        public Nullable<int> life_of_loan { get; set; }
        public Nullable<int> unit_day { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<int> month_payment_date { get; set; }
        public Nullable<System.DateTime> repayment_date { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public int companyid { get; set; }
        public string company_name { get; set; }
        public string agent_name { get; set; }
        public string agent_id_card { get; set; }
        public string username { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string realname { get; set; }
        public string iD_number { get; set; }
        public Nullable<int> payment_options { get; set; }
        public string legal_representative { get; set; }
        public Nullable<int> usertypes { get; set; }
        public string CopName { get; set; }
        public Nullable<decimal> registered_capital { get; set; }
        public Nullable<System.DateTime> Date_incorporation { get; set; }
        public string company_address { get; set; }
        public string company_profile { get; set; }
        public string business_licence { get; set; }
        public string business_certificate { get; set; }
        public string agent { get; set; }
        public string Tax_NO { get; set; }
        public string UsrCustId { get; set; }
        public string CardId { get; set; }
        public string UsrId { get; set; }
    }
}
