//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_bonus_account
    {
        public int bonus_account_id { get; set; }
        public Nullable<int> activity_schedule_id { get; set; }
        public string activity_schedule_name { get; set; }
        public Nullable<decimal> amount_of_reward { get; set; }
        public Nullable<decimal> use_lower_limit { get; set; }
        public Nullable<int> reward { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> reward_state { get; set; }
        public string reward_remarks { get; set; }
        public Nullable<System.DateTime> entry_time { get; set; }
        public Nullable<int> act_state { get; set; }
        public Nullable<int> proid { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
        public Nullable<int> membertable_registerid { get; set; }
        public string mobile { get; set; }
        public string iD_number { get; set; }
    }
}
