//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_borrowing_Bid_records_income_statement
    {
        public int targetid { get; set; }
        public decimal loan_number { get; set; }
        public string borrowing_title { get; set; }
        public Nullable<decimal> borrowing_balance { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public int income_statement_id { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public Nullable<decimal> annual_revenue { get; set; }
        public Nullable<System.DateTime> invest_time { get; set; }
        public Nullable<int> current_investment_period { get; set; }
        public Nullable<System.DateTime> value_date { get; set; }
        public Nullable<System.DateTime> interest_payment_date { get; set; }
        public Nullable<decimal> repayment_amount { get; set; }
        public Nullable<System.DateTime> repayment_period { get; set; }
        public Nullable<int> investor_registerid { get; set; }
        public Nullable<int> payment_status { get; set; }
        public int bid_records_id { get; set; }
        public Nullable<decimal> annual_interest_rate { get; set; }
        public int registerid { get; set; }
        public Nullable<decimal> available_balance { get; set; }
        public Nullable<int> payment_options { get; set; }
        public string BorrUsrCustId { get; set; }
        public string OutCustId { get; set; }
        public Nullable<decimal> bid_orderid { get; set; }
        public string SubOrdid { get; set; }
        public Nullable<System.DateTime> SubOrdDate { get; set; }
        public Nullable<decimal> loan_management_fee { get; set; }
        public string username { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<decimal> Principal { get; set; }
        public Nullable<decimal> interestpayment { get; set; }
        public string contractpath { get; set; }
        public string orderid { get; set; }
        public Nullable<int> current_period { get; set; }
    }
}
