//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Channel_Invite
    {
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<int> registerid { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
        public int ChannelID { get; set; }
        public string ChannelName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public byte Status { get; set; }
        public string AdminUserName { get; set; }
        public Nullable<System.DateTime> registration_time { get; set; }
        public Nullable<System.DateTime> invest_time { get; set; }
        public Nullable<int> ordstate { get; set; }
        public string channel_invitedcode { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<int> invest_state { get; set; }
        public int ID { get; set; }
        public string borrowing_title { get; set; }
        public string DeadLine { get; set; }
        public Nullable<int> DeadLineNumber { get; set; }
    }
}
