//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_contract_type_template
    {
        public int contract_template_id { get; set; }
        public string contract_template_name { get; set; }
        public string contract_template_context { get; set; }
        public Nullable<int> usestate { get; set; }
        public Nullable<System.DateTime> cretatetime { get; set; }
        public string contract_type_name { get; set; }
        public int contract_type_id { get; set; }
    }
}
