//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_hx_Bid_records_borrowing_target
    {
        public string borrowing_title { get; set; }
        public int bid_records_id { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<decimal> loan_number { get; set; }
        public Nullable<decimal> annual_interest_rate { get; set; }
        public Nullable<int> current_period { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<System.DateTime> value_date { get; set; }
        public Nullable<System.DateTime> investment_maturity { get; set; }
        public Nullable<System.DateTime> invest_time { get; set; }
        public Nullable<int> invest_state { get; set; }
        public Nullable<int> flow_return { get; set; }
        public Nullable<decimal> repayment_amount { get; set; }
        public Nullable<System.DateTime> repayment_period { get; set; }
        public Nullable<int> investor_registerid { get; set; }
        public Nullable<int> payment_status { get; set; }
        public Nullable<decimal> withoutinterest { get; set; }
        public Nullable<decimal> haveinterest { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
        public int registerid { get; set; }
        public Nullable<int> payment_options { get; set; }
        public Nullable<int> contractid { get; set; }
        public string contractpath { get; set; }
        public Nullable<int> life_of_loan { get; set; }
        public Nullable<int> unit_day { get; set; }
        public string mobile { get; set; }
        public string UsrCustId { get; set; }
        public Nullable<decimal> FrozenidAmount { get; set; }
        public string FrozenidNo { get; set; }
        public Nullable<int> FrozenState { get; set; }
        public string FreezeTrxId { get; set; }
        public string borrUsrCustid { get; set; }
        public decimal available_balance { get; set; }
        public Nullable<int> tender_state { get; set; }
        public string invitationcode { get; set; }
        public string borrealname { get; set; }
        public string borusername { get; set; }
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<decimal> borrowing_balance { get; set; }
        public Nullable<int> ordstate { get; set; }
        public Nullable<int> IsLoans { get; set; }
        public int project_type_id { get; set; }
        public decimal JiaxiNum { get; set; }
        public decimal BonusAmt { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<System.DateTime> repayment_date { get; set; }
        public Nullable<System.DateTime> registration_time { get; set; }
        public Nullable<int> Channelsource { get; set; }
        public string Tid { get; set; }
        public Nullable<decimal> service_charge { get; set; }
        public Nullable<int> useridentity { get; set; }
        public Nullable<int> usertypes { get; set; }
        public string iD_number { get; set; }
    }
}
