//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_invitation_record
    {
        public int invitationid { get; set; }
        public string invcode { get; set; }
        public Nullable<System.DateTime> invtime { get; set; }
        public Nullable<int> invpersonid { get; set; }
        public Nullable<int> Invpeopleid { get; set; }
        public Nullable<decimal> income { get; set; }
        public string award_description { get; set; }
        public Nullable<int> water_type { get; set; }
        public int registerid { get; set; }
        public string username { get; set; }
        public Nullable<int> ActTypeId { get; set; }
    }
}
