//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LL_Cash_User
    {
        public int LLcashid { get; set; }
        public string no_order { get; set; }
        public string dt_order { get; set; }
        public Nullable<decimal> money_order { get; set; }
        public string acct_name { get; set; }
        public string province_code { get; set; }
        public string city_code { get; set; }
        public string brabank_name { get; set; }
        public Nullable<System.DateTime> ordertime { get; set; }
        public string card_no { get; set; }
        public Nullable<int> paystate { get; set; }
        public Nullable<int> Usrid { get; set; }
        public int registerid { get; set; }
        public string username { get; set; }
        public string mobile { get; set; }
        public string BankName { get; set; }
        public string bank_code { get; set; }
        public Nullable<System.DateTime> OperTime { get; set; }
        public Nullable<int> h_state { get; set; }
        public Nullable<int> htype { get; set; }
    }
}
