//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LLPay_Re
    {
        public int Rechargeid { get; set; }
        public Nullable<int> UsrId { get; set; }
        public string no_order { get; set; }
        public string ordertime { get; set; }
        public string info_order { get; set; }
        public Nullable<decimal> money_order { get; set; }
        public string BankCode { get; set; }
        public string card_no { get; set; }
        public Nullable<int> ReState { get; set; }
        public string oid_paybill { get; set; }
        public int re_cashid { get; set; }
        public string OrdId { get; set; }
        public Nullable<decimal> TransAmt { get; set; }
        public Nullable<int> h_state { get; set; }
        public Nullable<int> htype { get; set; }
        public int registerid { get; set; }
        public Nullable<System.DateTime> OrdTime { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
    }
}
