//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LLBack_Card_List
    {
        public string BankCode { get; set; }
        public int bindCardid { get; set; }
        public Nullable<int> Usrid { get; set; }
        public string BankCard { get; set; }
        public Nullable<System.DateTime> Bindtime { get; set; }
        public Nullable<decimal> Re_Amt { get; set; }
        public Nullable<decimal> Quota { get; set; }
        public string Citycode { get; set; }
        public string branch { get; set; }
        public string no_agree { get; set; }
        public Nullable<int> cardstate { get; set; }
        public string BankName { get; set; }
        public string CardImage { get; set; }
        public string province_code { get; set; }
        public string realname { get; set; }
        public int registerid { get; set; }
    }
}
