//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Repayment_plan_loan_records
    {
        public int repayment_plan_id { get; set; }
        public string BorrUsrCustId { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<int> current_period { get; set; }
        public Nullable<System.DateTime> repayment_period { get; set; }
        public Nullable<int> repayment_type { get; set; }
        public Nullable<decimal> repayment_amount { get; set; }
        public Nullable<decimal> actual_amount_repayment { get; set; }
        public Nullable<int> repayment_state { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<decimal> interestpayment { get; set; }
        public Nullable<decimal> fees { get; set; }
        public Nullable<decimal> O_penalty { get; set; }
        public Nullable<decimal> shall_repayment { get; set; }
        public Nullable<decimal> pla_amt_generation { get; set; }
        public Nullable<decimal> Interest_spreads { get; set; }
        public string Rep_Remarks { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public int Loan_records_id { get; set; }
        public Nullable<int> bid_records_id { get; set; }
        public string InCustId { get; set; }
        public string OutCustId { get; set; }
        public Nullable<decimal> LoanAMT { get; set; }
        public string LoanOrdId { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public string SubOrdid { get; set; }
        public Nullable<System.DateTime> SubOrdDate { get; set; }
        public string unFreezeOrdId { get; set; }
        public string FreezeTrxId { get; set; }
        public Nullable<int> investor_registerid { get; set; }
        public decimal available_balance { get; set; }
    }
}
