//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_type_news
    {
        public int newid { get; set; }
        public Nullable<int> web_Type_menu_id { get; set; }
        public string News_title { get; set; }
        public string News_Key { get; set; }
        public string news_Des { get; set; }
        public string context { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> adminuserid { get; set; }
        public string menu_name { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> rootid { get; set; }
        public string path1 { get; set; }
        public Nullable<int> orderid { get; set; }
        public string topmenuname { get; set; }
        public Nullable<int> comm { get; set; }
        public Nullable<int> listcomm { get; set; }
        public string newimg { get; set; }
        public Nullable<int> ClickCount { get; set; }
    }
}
