//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserInvitation
    {
        public Nullable<int> invpersonid { get; set; }
        public string username { get; set; }
        public int invitationid { get; set; }
        public string invcode { get; set; }
        public Nullable<System.DateTime> invtime { get; set; }
        public Nullable<int> Invpeopleid { get; set; }
        public Nullable<int> InvitesStates { get; set; }
        public Nullable<decimal> Invitereward { get; set; }
        public Nullable<int> userstate { get; set; }
        public Nullable<System.DateTime> registration_time { get; set; }
        public Nullable<System.DateTime> invest_time { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
    }
}
