//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UsrBindCardBank
    {
        public int UsrBindCardID { get; set; }
        public string UsrCustId { get; set; }
        public string OpenAcctId { get; set; }
        public string OpenBankId { get; set; }
        public Nullable<int> defCard { get; set; }
        public string BankName { get; set; }
        public string Expr1 { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
        public int registerid { get; set; }
        public string CardImage { get; set; }
        public Nullable<int> Isquick { get; set; }
        public Nullable<int> Isordinary { get; set; }
        public string CardImageNew { get; set; }
        public Nullable<int> BindCardType { get; set; }
        public Nullable<int> isGren { get; set; }
    }
}
