//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Usr_Phone_adminUsr
    {
        public int registerid { get; set; }
        public string username { get; set; }
        public string mobile { get; set; }
        public string realname { get; set; }
        public Nullable<decimal> account_total_assets { get; set; }
        public Nullable<decimal> available_balance { get; set; }
        public Nullable<System.DateTime> registration_time { get; set; }
        public Nullable<System.DateTime> lastlogintime { get; set; }
        public Nullable<int> useridentity { get; set; }
        public Nullable<int> CommNum { get; set; }
        public Nullable<int> RechargeNum { get; set; }
        public Nullable<int> CashNum { get; set; }
        public Nullable<int> InvestNum { get; set; }
        public Nullable<int> LoginNum { get; set; }
        public Nullable<System.DateTime> calltime { get; set; }
        public int recordsid { get; set; }
        public string recordcontext { get; set; }
        public Nullable<System.DateTime> recordtime { get; set; }
        public string gtType { get; set; }
        public string problemType { get; set; }
        public string adminuser { get; set; }
    }
}
