//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_yaoqin_count
    {
        public int bid_records_id { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<int> ordstate { get; set; }
        public string invitationcode { get; set; }
        public string yaousername { get; set; }
        public int? yaouid { get; set; }
        public int invuid { get; set; }
        public string invusername { get; set; }
        public string realname { get; set; }
        public Nullable<System.DateTime> invest_time { get; set; }
        public string yaorealname { get; set; }
    }
}
