//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserCenter
    {
        public int registerid { get; set; }
        public string username { get; set; }
        public string UsrCustId { get; set; }
        public Nullable<int> isrealname { get; set; }
        public Nullable<System.DateTime> registration_time { get; set; }
        public string mobile { get; set; }
        public string realname { get; set; }
        public decimal available_balance { get; set; }
        public Nullable<int> usertypes { get; set; }
        public Nullable<int> investCount { get; set; }
        public int IsCPS { get; set; }

        public decimal allInvestMoney { get; set; }
        public int investcounts { get; set; }
        
        public string InvestState { get; set; }
    }
}
