//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewInvestDetail
    {
        public int recordId { get; set; }
        public Nullable<int> targetid { get; set; }
        public string targetTitle { get; set; }
        public Nullable<int> investMemberId { get; set; }
        public string investMemberName { get; set; }
        public Nullable<int> deadLine { get; set; }
        public Nullable<int> unitDay { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> borrowTotalAmount { get; set; }
        public Nullable<decimal> fundTotalAmount { get; set; }
        public Nullable<decimal> investAmount { get; set; }
        public Nullable<int> paymentOption { get; set; }
        public Nullable<int> paymentStatus { get; set; }
        public Nullable<System.DateTime> rateBeginOn { get; set; }
        public Nullable<System.DateTime> investMaturity { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> investNumber { get; set; }
        public Nullable<int> guarantee_way_id { get; set; }
        public Nullable<int> month_payment_date { get; set; }
        public Nullable<decimal> jiaxiNum { get; set; }
        public Nullable<decimal> BonusAmt { get; set; }
    }
}
