//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BId_userAct
    {
        public int bid_records_id { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<decimal> loan_number { get; set; }
        public Nullable<decimal> annual_interest_rate { get; set; }
        public Nullable<int> current_period { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<decimal> OrdId { get; set; }
        public Nullable<decimal> BonusAmt { get; set; }
        public Nullable<decimal> JiaxiNum { get; set; }
        public int UserAct { get; set; }
        public Nullable<int> registerid { get; set; }
        public Nullable<int> ActID { get; set; }
        public Nullable<int> RewTypeID { get; set; }
        public Nullable<int> ActTypeId { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> Uselower { get; set; }
        public Nullable<decimal> Usehight { get; set; }
        public Nullable<System.DateTime> AmtEndtime { get; set; }
        public Nullable<int> AmtUses { get; set; }
        public Nullable<int> UseState { get; set; }
        public Nullable<int> AmtProid { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
        public Nullable<int> ISSmsOne { get; set; }
        public Nullable<int> IsSmsThree { get; set; }
        public Nullable<int> IsSmsSeven { get; set; }
        public Nullable<int> isSmsFifteen { get; set; }
        public Nullable<int> isSmsSixteen { get; set; }
        public string username { get; set; }
        public string mobile { get; set; }
        public string realname { get; set; }
        public Nullable<int> useridentity { get; set; }
        public Nullable<int> Channelsource { get; set; }
    }
}
