//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTargetWithRecord
    {
        public int targetid { get; set; }
        public string borrowing_title { get; set; }
        public Nullable<int> borrower_registerid { get; set; }
        public string username { get; set; }
        public Nullable<int> tender_state { get; set; }
        public Nullable<System.DateTime> repayment_date { get; set; }
        public Nullable<int> month_payment_date { get; set; }
        public int project_type_id { get; set; }
        public Nullable<decimal> borrowing_balance { get; set; }
        public Nullable<decimal> annual_interest_rate { get; set; }
        public Nullable<int> life_of_loan { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<int> unit_day { get; set; }
        public Nullable<int> payment_options { get; set; }
        public Nullable<decimal> H_Repayment_Amt { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> invest_num { get; set; }
        public Nullable<decimal> fundraising_amount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> indexorder { get; set; }
        public Nullable<decimal> minimum { get; set; }
        public Nullable<decimal> maxmum { get; set; }
        public Nullable<System.DateTime> sys_time { get; set; }
    }
}
