//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewThirdWangDaiZhongGuo
    {
        public string url { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<decimal> account { get; set; }
        public Nullable<decimal> apr { get; set; }
        public Nullable<int> limit { get; set; }
        public Nullable<int> limit_type { get; set; }
        public Nullable<int> way { get; set; }
        public Nullable<decimal> account_yes { get; set; }
        public Nullable<decimal> account_min { get; set; }
        public Nullable<decimal> account_max { get; set; }
        public string username { get; set; }
        public Nullable<int> add_time { get; set; }
        public Nullable<int> verify_time { get; set; }
        public Nullable<int> success_time { get; set; }
        public string type { get; set; }
        public Nullable<int> status { get; set; }
        public string reward { get; set; }
        public int is_diya { get; set; }
        public int is_danbao { get; set; }
        public int is_mima { get; set; }
        public int is_miao { get; set; }
        public int is_zhuan { get; set; }
    }
}
