//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserInviteInfor
    {
        public int invitationid { get; set; }
        public Nullable<int> InviteId { get; set; }
        public string InviteName { get; set; }
        public string InviteRealName { get; set; }
        public Nullable<int> InvitedId { get; set; }
        public string InvitedName { get; set; }
        public string InvitedRealName { get; set; }
        public string InviteCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> InvestedOn { get; set; }
        public Nullable<decimal> InvestAmount { get; set; }
        public Nullable<decimal> OrderId { get; set; }
        public string BorrowTitle { get; set; }
        public string DeadLine { get; set; }
        public Nullable<int> DeadLineNumber { get; set; }
        public int IsBindedCard { get; set; }
    }
}
