//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDetailsReport
    {
        public int registerid { get; set; }
        public string mobile { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
        public Nullable<System.DateTime> registration_time { get; set; }
        public Nullable<int> useridentity { get; set; }
        public decimal InvestAllMoney { get; set; }
        public decimal FoldAllMoney { get; set; }
        public Nullable<decimal> RechargeAllMoney { get; set; }
        public string IsFirstInvest { get; set; }
        public decimal JanMoney { get; set; }
        public decimal MarMoney { get; set; }
        public decimal JunMoney { get; set; }
    }
}
