//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuangLitouP2P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewInvestRecord
    {
        public int bid_records_id { get; set; }
        public Nullable<int> targetid { get; set; }
        public Nullable<int> investor_registerid { get; set; }
        public string username { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<int> invest_state { get; set; }
        public Nullable<System.DateTime> invest_time { get; set; }
        public Nullable<int> ordstate { get; set; }
    }
}
