//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuanglitouP2P.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportErrorDataForIn
    {
        public int registerid { get; set; }

        public string mobile { get; set; }

        public string realname { get; set; }

        public string username { get; set; }

        public Nullable<System.DateTime> registration_time { get; set; }

        public string InvestState { get; set; }

        public decimal allInvestMoney { get; set; }

        public Nullable<int> investCount { get; set; }

        public string errorreason { get; set; }
        
    }
}
