//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webdiyer.WebControls.Mvc {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcPagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcPagerResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Webdiyer.WebControls.Mvc.MvcPagerResources", typeof(MvcPagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Container tag name cannot be null or empty 的本地化字符串。
        /// </summary>
        internal static string ContainerTagNameCannotBeNull {
            get {
                return ResourceManager.GetString("ContainerTagNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!--MvcPager v3.0.1 for ASP.NET MVC 4.0+ © 2009-2015 Webdiyer (http://en.webdiyer.com)--&gt; 的本地化字符串。
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        internal static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page index is invalid 的本地化字符串。
        /// </summary>
        internal static string InvalidPageIndexErrorMessage {
            get {
                return ResourceManager.GetString("InvalidPageIndexErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page index is out of range 的本地化字符串。
        /// </summary>
        internal static string PageIndexOutOfRangeErrorMessage {
            get {
                return ResourceManager.GetString("PageIndexOutOfRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev 的本地化字符串。
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
    }
}
